import FilterComponent from "@/components/FilterComponent";
import Navbar from "@/components/Navbar";
import ProductItem from "@/components/ProductItem";
import { Grid } from "@mui/material";
import Box from "@mui/material/Box";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <FilterComponent />
        <Grid
          container
          spacing={2}
          margin={"20px"}
          marginTop={"170px"}
          mr={"-17px"}
        >
          {[...Array(6)].map((_, index: number) => (
            <Grid item key={index} xs={12} sm={6} md={4}>
              <ProductItem />
            </Grid>
          ))}
        </Grid>
      </Box>
    </>
  );
}
